### ISSUE TITLE
i have this error while running the code

### ISSUE THREAD

**Issue by pratham773** [mrthundergod/Newspaper-Sentiment-Analysis#1]
python mainv2.py
/home/prathamesh/miniconda3/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

Hello! Welcome to the News Reader and Analysis App!
Select from the following Categories.
 1. National News. 
 2. International News. 
 3. State News. 
 4. Science News. 
 5. Business News
1

 HELLO!!! What do you wanna do know? : 
 1. See News 
 2. See Sentiment Value for National News 
 3. See overall Sentiment for now. 

Enter the number: 1
Traceback (most recent call last):
  File "mainv2.py", line 55, in <module>
    titles, links = parser(soup)
  File "/home/prathamesh/Desktop/Newspaper-Sentiment-Analysis-master/pageScraper.py", line 17, in parser
    title = news.h3.text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by mrthundergod** [comment]
Hey, Sorry for the delay. Which version of Python are you using? I haven't tried it with 3.7. I will get back to you after trying that out.

**Comment by kavithaspatil** [comment]
hi i have an error showing the following
 HELLO!!! What do you wanna do know? : 
 1. See News 
 2. See Sentiment Value for National News 
 3. See overall Sentiment for now. 

Enter the number: 1
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\Newspaper-Sentiment-Analysis-master (2)\mainv2.py", line 54, in <module>
    soup = soupee(url)
  File "C:\Users\DELL\Desktop\Newspaper-Sentiment-Analysis-master (2)\pageScraper.py", line 9, in soupee
    sauce=urllib.request.urlopen(url)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by pratham773** [comment]
ok

**Comment by mrthundergod** [comment]
@kavithaspatil @pratham773  Hey, so sorry for the delays, i will look into this and fix them by this week itself!

**Comment by Jazzyao** [comment]
Traceback (most recent call last):
  File "main2.py", line 55, in <module>
    url = urlMaker(mainUrl, x)
NameError: name 'urlMaker' is not defined
 hey I have a issue running the code

**Comment by Jazzyao** [comment]
do you know why is it?

**Comment by Swapy-0825** [comment]
Enter the number: 1
Traceback (most recent call last):
  File "mainv2.py", line 55, in <module>
    soup = soupee(url)
  File "C:\Users\Swapnil Shrivastava\Desktop\Newspaper-Sentiment-Analysis-master\pageScraper.py", line 9, in soupee
    sauce=urllib.request.urlopen(url)
  File "C:\Users\Swapnil Shrivastava\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Swapnil Shrivastava\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Swapnil Shrivastava\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Swapnil Shrivastava\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Swapnil Shrivastava\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Swapnil Shrivastava\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden


SAME PROBLEM...CAN YOU TELL ME HOW TO RESOLVE IT
